
const data = [
    {
        id: 1,
        month: "January",
        venue: "Madison Square Garden",
        artist: "Billy Joel",
        mevent: "Live At The Garden",
        type: "CD",
        price: 25,
        image: '../images/billy-joel-cd.png',
    },
    {
        id: 2,
        month: "January",
        venue: "Madison Square Garden",
        artist: "Billy Joel",
        mevent: "Live At The Garden",
        type: "T-Shirt",
        price: 45,
        image: "../images/billy-joel-tshirt.png",
    },
    {
        id: 3,
        month: "January",
        venue: "Madison Square Garden",
        artist: "Billy Joel",
        mevent: "Live At The Garden",
        type: "Signed Poster",
        price: 100,
        image: "../images/billy-joel-poster.png",
    },
    {
        id: 4,
        month: "February",
        venue: "UBS Arena",
        artist: "Kanye West",
        mevent: "VULTURES LISTENING PARTY",
        type: "CD",
        price: 20,
        image: "../images/vultures-kanye-cd.png",
    },
    {
        id: 5,
        month: "February",
        venue: "UBS Arena",
        artist: "Kanye West",
        mevent: "VULTURES LISTENING PARTY",
        type: "T-Shirt",
        price: 30,
        image: "../images/vultures-kanye-tshirt.png",
    },
    {
        id: 6,
        month: "February",
        venue: "UBS Arena",
        artist: "Kanye West",
        mevent: "VULTURES LISTENING PARTY",
        type: "Signed Poster",
        price: 120,
        image: "../images/vultures-kanye-poster.png",
    },
    {
        id: 7,
        month: "March",
        venue: "UBS Arena",
        artist: "Drake and 21 Savage",
        mevent: "It's All A Blur Tour",
        type: "CD",
        price: 25,
        image: "../images/drake-cd.png",
    },
    {
        id: 8,
        month: "March",
        venue: "UBS Arena",
        artist: "Drake and 21 Savage",
        mevent: "It's All A Blur Tour",
        type: "T-Shirt",
        price: 40,
        image: "../images/drake-tshirt.png",
    },
    {
        id: 9,
        month: "March",
        venue: "UBS Arena",
        artist: "Drake and 21 Savage",
        mevent: "It's All A Blur Tour",
        type: "Signed Poster",
        price: 150,
        image: "../images/drake-poster.png",
    },
    {
        id: 10,
        month: "April",
        venue: "Madison Square Garden",
        artist: "Olivia Rodrigo",
        mevent: "GUTS World Tour",
        type: "CD",
        price: 20,
        image: "../images/olivia-rodrigo-cd.png",
    },
    {
        id: 11,
        month: "April",
        venue: "Madison Square Garden",
        artist: "Olivia Rodrigo",
        mevent: "GUTS World Tour",
        type: "T-Shirt",
        price: 40,
        image: "../images/olivia-rodrigo-tshirt.png",
    },
    {
        id: 12,
        month: "April",
        venue: "Madison Square Garden",
        artist: "Olivia Rodrigo",
        mevent: "GUTS World Tour",
        type: "Signed Poster",
        price: 450,
        image: "../images/olivia-rodrigo-poster.png",
    },
    {
        id: 13,
        month: "May",
        venue: "MetLife Stadium",
        artist: "The Rolling Stones",
        mevent: "Hackney Diamonds Tour",
        type: "CD",
        price: 14,
        image: "../images/rolling-stones-cd.png",
    },
    {
        id: 14,
        month: "May",
        venue: "MetLife Stadium",
        artist: "The Rolling Stones",
        mevent: "Hackney Diamonds Tour",
        type: "T-Shirt",
        price: 50,
        image: "../images/rolling-stones-tshirt.png",
    },
    {
        id: 15,
        month: "May",
        venue: "MetLife Stadium",
        artist: "The Rolling Stones",
        mevent: "Hackney Diamonds Tour",
        type: "Signed Poster",
        price: 270,
        image: "../images/rolling-stones-poster.png",
    },
    {
        id: 16,
        month: "June",
        venue: "Madison Square Garden",
        artist: "Justin Timberlake",
        mevent: "The Forget Tomorrow World Tour",
        type: "CD",
        price: 14,
        image: "../images/justin-timberlake-cd.png",
    },
    {
        id: 17,
        month: "June",
        venue: "Madison Square Garden",
        artist: "Justin Timberlake",
        mevent: "The Forget Tomorrow World Tour",
        type: "T-Shirt",
        price: 28,
        image: "../images/justin-timberlake-tshirt.png",
    },
    {
        id: 18,
        month: "June",
        venue: "Madison Square Garden",
        artist: "Justin Timberlake",
        mevent: "The Forget Tomorrow World Tour",
        type: "Signed Poster",
        price: 100,
        image: "../images/justin-timberlake-poster.png",
    },
    {
        id: 19,
        month: "July",
        venue: "MetLife Stadium",
        artist: "Luke Combs",
        mevent: "Growin' Up And Gettin' Old Tour",
        type: "CD",
        price: 14,
        image: "../images/luke-combs-cd.png",
    },
    {
        id: 20,
        month: "July",
        venue: "MetLife Stadium",
        artist: "Luke Combs",
        mevent: "Growin' Up And Gettin' Old Tour",
        type: "T-Shirt",
        price: 30,
        image: "../images/luke-combs-tshirt.png",
    },
    {
        id: 21,
        month: "July",
        venue: "MetLife Stadium",
        artist: "Luke Combs",
        mevent: "Growin' Up And Gettin' Old Tour",
        type: "Signed Poster",
        price: 200,
        image: "../images/luke-combs-poster.png",
    },
    {
        id: 22,
        month: "August",
        venue: "Madison Square Garden",
        artist: "Tate McRae",
        mevent: "Think Later Tour",
        type: "CD",
        price: 20,
        image: "../images/tate-mcrae-cd.png",
    },
    {
        id: 23,
        month: "August",
        venue: "Madison Square Garden",
        artist: "Tate McRae",
        mevent: "Think Later Tour",
        type: "T-Shirt",
        price: 50,
        image: "../images/tate-mcrae-tshirt.png",
    },
    {
        id: 24,
        month: "August",
        venue: "Madison Square Garden",
        artist: "Tate McRae",
        mevent: "Think Later Tour",
        type: "Signed Poster",
        price: 350,
        image: "../images/tate-mcrae-poster.png",
    },
    {
        id: 25,
        month: "September",
        venue: "Madison Square Garden",
        artist: "Charli XCX, Troye Sivan",
        mevent: "Sweat",
        type: "CD",
        price: 25,
        image: "../images/charli-troye-cd.png",
    },
    {
        id: 26,
        month: "September",
        venue: "Madison Square Garden",
        artist: "Charli XCX, Troye Sivan",
        mevent: "Sweat",
        type: "T-Shirt",
        price: 50,
        image: "../images/charli-troye-tshirt.png",
    },
    {
        id: 27,
        month: "September",
        venue: "Madison Square Garden",
        artist: "Charli XCX, Troye Sivan",
        mevent: "Sweat",
        type: "Signed Poster",
        price: 60,
        image: "../images/charli-troye-poster.png",
    },
    {
        id: 28,
        month: "October",
        venue: "MetLife Stadium",
        artist: "Travis Scott",
        mevent: "One Night Only in Utopia",
        type: "CD",
        price: 20,
        image: "../images/travis-scott-cd.png",
    },
    {
        id: 29,
        month: "October",
        venue: "MetLife Stadium",
        artist: "Travis Scott",
        mevent: "One Night Only in Utopia",
        type: "T-Shirt",
        price: 50,
        image: "../images/travis-scott-tshirt.png",
    },
    {
        id: 30,
        month: "October",
        venue: "MetLife Stadium",
        artist: "Travis Scott",
        mevent: "One Night Only in Utopia",
        type: "Signed Poster",
        price: 70,
        image: "../images/travis-scott-poster.png",
    },
    {
        id: 31,
        month: "October/November",
        venue: "Madison Square Garden",
        artist: "Billie Eilish",
        mevent: "Hit Me Hard and Soft: The Tour",
        type: "CD",
        price: 25,
        image: "../images/billie-eilish-cd.png",
    },
    {
        id: 32,
        month: "October/November",
        venue: "Madison Square Garden",
        artist: "Billie Eilish",
        mevent: "Hit Me Hard and Soft: The Tour",
        type: "T-Shirt",
        price: 100,
        image: "../images/billie-eilish-tshirt.png",
    },
    {
        id: 33,
        month: "October/November",
        venue: "Madison Square Garden",
        artist: "Billie Eilish",
        mevent: "Hit Me Hard and Soft: The Tour",
        type: "Signed Poster",
        price: 370,
        image: "../images/billie-eilish-poster.png",
    },
    {
        id: 34,
        month: "Upcoming Concert December",
        venue: "Madison Square Garden",
        artist: "Katy Perry, Twenty One Pilots",
        mevent: "IHeartRadio Jingle Ball",
        type: "Tickets",
        price: 750,
        image: "../images/jingle-ball-tickets.png",
    },
    {
        id: 35,
        month: "Upcoming Concert December",
        venue: "Madison Square Garden",
        artist: "Katy Perry, Twenty One Pilots",
        mevent: "IHeartRadio Jingle Ball",
        type: "T-Shirt",
        price: 25,
        image: "../images/jingle-ball-tshirt.png",
    },
    {
        id: 36,
        month: "Upcoming Concert December",
        venue: "Madison Square Garden",
        artist: "Katy Perry, Twenty One Pilots",
        mevent: "IHeartRadio Jingle Ball",
        type: "Wheezer Backstage Passes",
        price: 1250,
        image: "../images/jingle-ball-poster.png",
    }
];


export default data;
